name: Release Workflow Agenda

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  Detectar nova versão:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Mostrar referência completa
        run: echo "Referência completa: $GITHUB_REF"

      - name: Mostrar nome simplificado da tag
        run: echo "Tag simplificada: ${GITHUB_REF_NAME}"

      - name: Exemplo - gerar log da versão
        run: echo "Gerando release da versão ${GITHUB_REF_NAME}"
